// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdr6S7OWd1gp398Y5YmQq48wSPojdTdXE',
    appId: '1:665619868927:web:7e84b258f2d0694e9970ca',
    messagingSenderId: '665619868927',
    projectId: 'budget-tracker-68836',
    authDomain: 'budget-tracker-68836.firebaseapp.com',
    storageBucket: 'budget-tracker-68836.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4FIew-9wtPXZV5aTjrO7YXX7WF_HOZM',
    appId: '1:665619868927:android:e7d8b08caf10ebbf9970ca',
    messagingSenderId: '665619868927',
    projectId: 'budget-tracker-68836',
    storageBucket: 'budget-tracker-68836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2m2JuHrilPVZCIyTuezTDpuyTvGgExd8',
    appId: '1:665619868927:ios:ecfe946fa91cca949970ca',
    messagingSenderId: '665619868927',
    projectId: 'budget-tracker-68836',
    storageBucket: 'budget-tracker-68836.appspot.com',
    iosClientId: '665619868927-skppu2gh942buckbsui45mpcf9c78c36.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2m2JuHrilPVZCIyTuezTDpuyTvGgExd8',
    appId: '1:665619868927:ios:d5d809d6043a80ed9970ca',
    messagingSenderId: '665619868927',
    projectId: 'budget-tracker-68836',
    storageBucket: 'budget-tracker-68836.appspot.com',
    iosClientId: '665619868927-1sbrm1an9qoh7idrog74a2vo42v28bff.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracker.RunnerTests',
  );
}
